# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105obh_atayq5ALl5C_sLbLBKcu3SNBC9
"""

!pip install streamlit pandas matplotlib

# save this as streamlit_app.py later!
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title("Barça Player Stats Dashboard")

# Sample data
data = {
    'Player': ['Pedri', 'Gavi', 'Frenkie de Jong'],
    'Passing Accuracy': [90, 86, 92],
    'Tackles': [22, 34, 18],
    'Key Passes': [30, 25, 28]
}
df = pd.DataFrame(data)
# Player selection
player = st.selectbox("Select a Player", df['Player'])

# Show stats
player_data = df[df['Player'] == player].iloc[0]
st.write(f"**Passing Accuracy**: {player_data['Passing Accuracy']}%")
st.write(f"**Tackles**: {player_data['Tackles']}")
st.write(f"**Key Passes**: {player_data['Key Passes']}")

# Bar chart
fig, ax = plt.subplots()
ax.bar(['Passing', 'Tackles', 'Key Passes'],[player_data['Passing Accuracy'],player_data['Tackles'],player_data['Key Passes']])
ax.set_title(f"{player}'s Stats")
st.pyplot(fig)